[tool.poetry]
name = "cfavorita"
version = "0.1.0"
description = ""
authors = ["ivallesp <ivanvallesperez@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
numpy = "=1.16.2"
pandas = "=0.24.2"
tensorflow = "=1.13.1"
tensorboard = "=1.13.1"
kaggle = "=1.5.3"

[tool.poetry.dev-dependencies]
ipython = "^7.8"
ipykernel = "^5.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
