[tool.poetry]
name = "cfavorita"
version = "0.1.0"
description = ""
authors = ["ivallesp <ivanvallesperez@gmail.com>"]

[tool.poetry.dependencies]
python = "=3.7.3"
numpy = "=1.16.2"
pandas = "=0.24.2"
tensorboard = "=1.13.1"
kaggle = "=1.5.3"
pyarrow = "^0.15.0"
torch = "=1.3.0"
torchvision = "0.4.1"
matplotlib = "^3.1"
tensorboardX = "^1.9"

[tool.poetry.dev-dependencies]
black = {version = "^18.3-alpha.0", allows-prereleases = true}
flake8 = "^3.7"
ipython = "^7.8"
ipykernel = "^5.1"
tables = "^3.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
