[config]
batch_size          = 128
cuda                = true
forecasting_horizon = 16
learning_rate       = 0.0001
n_epochs            = 2000
n_history_ts        = 200
n_threads           = 8
random_seed         = 655325
sample              = false
