[config]
batch_size       = 64
cuda             = true
forecast_horizon = 16
learning_rate    = 0.0001
dropout          = 0.1
n_epochs         = 2000
n_threads        = 8
random_seed      = 655322
sample           = false
n_history_ts     = 375
